config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  # resources :home, only: [:index]
  resources :coins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/breadcrumb.rb
class Breadcrumb
  attr_reader :label, :path

  def initialize(label, path)
    @label = label
    @path = path
  end

  def link?
    @path.present?
  end
end

app/models/coin.rb
class Coin < ApplicationRecord
  belongs_to :mining_type
  validates :description, :acronym, :image, presence: true
  has_one_attached :image

  def image_as_icon
    image.variant(resize_to_limit: [25,25]).processed
  end

  def image_as_thumbnail
    image.variant(resize_to_limit: [300,300]).processed
  end
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
  has_many :coins
  validates :description, :acronym, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  helper_method :breadcrumbs

  def breadcrumbs
    @breadcrumbs ||= []
  end

  def add_breadcrumb(label, path = nil)
    breadcrumbs << Breadcrumb.new(label, path)
  end

  private

  def set_locale
    update_locale(params[:locale] || cookies[:locale])
  end

  def update_locale(locale)
    return if locale.blank? || I18n.locale == locale

    cookies[:locale] = locale
    I18n.locale = locale
  end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :fetch_coin, only: %i[ show edit update destroy ]
  before_action :fetch_mining_types, only: %i[ edit new create update]
  before_action :set_breadcrumbs

  def index
    @coins = Coin.all
  end

  def show
    add_breadcrumb(@coin.description, edit_coin_path(@coin))
  end

  def new
    @coin = Coin.new
    add_breadcrumb( t('.new_coin'))
  end

  def edit
    add_breadcrumb(@coin.description)
  end

  def create
    @coin = Coin.new(coin_params)

    if @coin.save
      redirect_to coins_path, notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @coin.update(coin_params)
      redirect_to coins_path, notice: t('.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @coin.destroy!
    redirect_to coins_url, notice: t('.success')
  end

  private
    def coin_params
      params.require(:coin).permit(:description, :acronym, :image, :mining_type_id,)
    end

    def fetch_coin
      @coin = Coin.find(params[:id])
    end

    def fetch_mining_types
      @all_mining_types = MiningType.all.pluck(:description, :id)
    end

    def set_breadcrumbs
      add_breadcrumb( t('breadcrumbs.home'), root_path)
      add_breadcrumb( t('breadcrumbs.coins'), coins_path)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @nome = params[:nome]
  end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :fetch_mining_type, only: %i[ show edit update destroy ]
  before_action :set_breadcrumbs

  def index
    @mining_types = MiningType.all
  end

  def show
    add_breadcrumb(@mining_type.description, edit_mining_type_path(@mining_type))
  end

  def new
    @mining_type = MiningType.new
    add_breadcrumb( t('.new_mining_type'))
  end

  def edit
    add_breadcrumb(@mining_type.description)
  end

  def create
    @mining_type = MiningType.new(mining_type_params)

    if @mining_type.save
      redirect_to mining_types_path, notice: t('.success')
    else
      render( :new, status: :unprocessable_entity )
    end
  end

  def update
    if @mining_type.update(mining_type_params)
      redirect_to mining_types_path, notice: t('.success')
    else
      render( :edit, status: :unprocessable_entity )
    end
  end

  def destroy
    @mining_type.destroy!
    redirect_to mining_types_url, notice: t('.success')
  end

  private

    def fetch_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end

    def set_breadcrumbs
      add_breadcrumb( t('breadcrumbs.home'), root_path)
      add_breadcrumb( t('breadcrumbs.mining_types'), mining_types_path)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def locale_set_flag
    I18n.locale.to_s == 'pt-BR' ? '&#x1F1E7&#x1F1F7'.html_safe : '&#x1F1FA&#x1F1F8'.html_safe
  end  
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/views/coins/_form.html.erb
<%= render 'shared/notifications/form_errors', object: @coin %>
<%= form_with(model: coin) do |form| %>
  <div class="flex justify-center">
    <div class="w-full p-5">
      <div>
        <%= form.label :description, t('.labels.description'), class: 'form-label' %>
        <%= form.text_field :description,  placeholder: t('.placeholders.description'), class: 'form-input' %> 
      </div>
      <div>
        <%= form.label :acronym, t('.labels.acronym'), class: 'form-label' %>
        <%= form.text_field :acronym, placeholder: t('.placeholders.acronym'), class: 'form-input' %>
      </div>
      <div>
        <%= form.label :image, t('.labels.image'), class: 'form-label' %>
        <%= form.file_field :image, class: "form-input-file", accept: 'image/png,image/jpeg' %>
      </div>
      <div>
        <%= form.label :mining_type_id, t('.labels.mining_type'), class: "form-label-select" %>
      </div>
      <div class="flex flex-row items-center justify-between gap-2">
          <%= form.select :mining_type_id, @all_mining_types, { include_blank: 'Selecione...' }, class: "form-input-select" %>
          <%= form.submit t('.submit'), type: :submit, class: "w-1/4 bg-blue-500 hover:bg-blue-700 text-white py-1 px-4 rounded cursor-pointer" %>
          <%= link_to t('.back'), coins_path, type: :button, class: "w-1/4 text-center bg-blue-500 hover:bg-blue-700 text-white py-1 px-4 rounded cursor-pointer" %>
      </div>
    </div>
  </div>
<% end %>

app/views/coins/edit.html.erb
<div class="w-full flex justify-center pt-5">
  <div class="relative flex flex-col w-[95%] sm:w-[75%] md:w-[50%] lg:w-[40%] xl:w-[25%] p-5 justify-center bg-gray-800 rounded-xl">
    <div class="flex justify-between px-5 items-center">
      <h1 class="text-white text-2xl"><%= t('.edit_coin') %> <strong>#<%= @coin.id %></strong> </h1>
      <div data-controller="popover">
        <template data-popover-target="content">
          <div data-popover-target="card" class="inline-block invisible sm:visible left-1/2 transform translate-x-[25%] top-[14%] absolute w-64 text-sm border rounded-lg shadow-sm text-gray-400 bg-gray-800 border-gray-600">
            <div class="p-4">
              <p class="text-base font-semibold leading-none text-gray-900 dark:text-white"><%= t('.tip') %></p>
              <p class="text-sm"> <%= t('.tip_text') %></p>
            </div>
          </div>
        </template>
          <i data-action="mouseenter->popover#show mouseleave->popover#hide">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none" viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              class="w-6 h-6 text-white hover:text-cw-purple-500">
              <path stroke-linecap="round" stroke-linejoin="round" d="m11.25 11.25.041-.02a.75.75 0 0 1 1.063.852l-.708 2.836a.75.75 0 0 0 1.063.853l.041-.021M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9-3.75h.008v.008H12V8.25Z" />
            </svg>
          </i>
      </div>
    </div>
    <%= render "form", coin: @coin %>
  </div>
</div>

app/views/coins/index.html.erb
<div class="w-full flex justify-center pt-6">
  <div class="w-full sm:w-[75%] md:w-[75%] lg:w-[50%] xl:w-[40%] overflow-x-auto shadow-md rounded-lg">
      <table class="w-full text-sm text-left rtl:text-right text-gray-400">
            <caption class="text-gray-900/80 bg-pattern-tpgraphy bg-current p-5 text-left">
              <div class="flex flex-row justify-between items-center">
                <p class="text-white text-lg font-semibold"><%= t('.crypto_coins') %></p>
                  <%= link_to t('.new_coin'), new_coin_path, class: "bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded" %>
              </div>
              <p class="mt-1 text-sm font-normal text-gray-400"> <%= t('.crypto_text') %></p>
            </caption>
          <thead class="text-xs uppercase bg-gray-700 text-gray-400">
              <tr>
                  <th scope="row" class="px-2 py-2"><%= t('.crypto_coins') %></th>
                  <th scope="row" class="px-2 py-2"><%= t('.acronym') %></th>
                  <th scope="row" class="px-6 py-2 text-center"><%= t('.icon') %></th>
                  <th scope="row" class="px-2 py-2"><%= t('.mining_type') %></th>
                  <th scope="row" class="px-2 py-2 text-right" rowspan="2"><%= t('.show_edit') %> </th>
              </tr>
          </thead>
          <tbody>
            <% @coins.each do |coin| %>
              <tr class="border-b bg-gray-800 border-gray-700 hover:bg-gray-600">
                  <td class="px-2 py-2 font-medium whitespace-nowrap text-white">
                    <%= coin.description %>
                  </td>
                  <td class="px-2 py-2">
                    <%= coin.acronym %>
                  </td>
                  <td class="px-6 py-2 flex justify-center">
                    <%= image_tag coin.image_as_icon, class: 'rounded-full', alt: "#{coin.description.titleize} icon" %>
                  </td>
                  <td class="px-2 py-2">
                    <%= coin.mining_type.description %>
                  </td>
                  <td class="px-2 py-2 flex justify-end space-x-2">
                    <%= link_to coin do %>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke-width="1.5"
                        stroke="currentColor"
                        class="w-7 h-7 hover:text-cw-purple-500 ease-out duration-500">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m15.75 15.75-2.489-2.489m0 0a3.375 3.375 0 1 0-4.773-4.773 3.375 3.375 0 0 0 4.774 4.774ZM21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                      </svg>
                    <% end %>
                    <%= link_to edit_coin_path(coin) do %>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke-width="1.5"
                        stroke="currentColor"
                        class="w-7 h-7 hover:text-cw-purple-500 ease-out duration-500">
                      <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
                      </svg>
                    <% end %>
                  </td>
              </tr>
            <% end %>
          </tbody>
      </table>
  </div>
</div>

app/views/coins/new.html.erb
<div class="w-full flex justify-center pt-5">
  <div class="flex flex-col p-6 w-[95%] sm:w-[75%] md:w-[50%] lg:w-[40%] xl:w-[25%] justify-center bg-gray-800 rounded-xl">
    <h1 class="text-white text-2xl pl-5"><%= t('.new_coin') %></h1>
    <%= render "form", coin: @coin %>
  </div>
</div>

app/views/coins/show.html.erb
<div class="w-full flex justify-center pt-5">
  <div class="flex flex-col p-6 w-[95%] sm:w-[75%] md:w-[50%] lg:w-[40%] xl:w-[25%] justify-center items-center bg-gray-800 rounded-xl">
    <h1 class="text-white text-4xl pl-5"><%= @coin.description.titleize %> - <%= @coin.mining_type.acronym %></h1>
    <div>
      <%= image_tag @coin.image_as_thumbnail %>
      <%= link_to @coin.image, target: "_blank", alt: "#{@coin.description.titleize} logo" do %>
        <span class="flex my-3 text-white text-sm hover:text-cw-purple-500 hover:underline items-center justify-center">
          <p><%= t('.image_full_size') %></p>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="w-6 h-6 mx-1">
            <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
          </svg>
        </span>
      <% end %>
    </div>
    <div>
      <%= link_to t('.back'), coins_path, type: :button, class: "w-1/2 text-center bg-blue-500 hover:bg-blue-700 text-white py-1 px-4 rounded cursor-pointer" %>
      <%= link_to t('.destroy'), coin_path, data: {'turbo-method': :delete, 'turbo-confirm': t('alerts.confirmation_msg')}, type: :button, class: "w-1/2 text-center bg-red-500 hover:bg-red-700 text-white py-1 px-4 rounded cursor-pointer" %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="text-white py-4 px-10 sm:px-20">
  <h1 class="text-4xl font-bold my-2"><%= t('.wellcome') %></h1>
  <p class="text-lg my-2"><%= t('.crypto_text') %></p>
  <hr>
  <div class="py-4 flex flex-col sm:flex-row w-full sm:w-100">
    <%= link_to t('.cripto_coins'), coins_path, class: "btn-links" %>
    <%= link_to t('.mining_types'), mining_types_path, class: "btn-links" %>
  </div>
  <div class="flex justify-center flex-col gap-6 sm:flex-row">
    <img src="https://i.imgur.com/5rOyTIm.png" alt="Crypto Wallet" class="w-full lg:w-full xl:w-[30%] rounded-3xl">
    <img src="https://i.imgur.com/qAc5VtB.png" alt="Crypto Wallet" class="w-full lg:w-full xl:w-[30%] rounded-3xl">
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="w-full flex justify-center py-2 sm:py-2 border-t shadow bg-cw-purple-900 border-gray-600">
  <span class="flex flex-col items-center text-gray-400">
    <div data-controller="popover">
      <template data-popover-target="content">
        <div class="">
          <div data-popover-target="card" class="inline-block invisible sm:visible left-1/2 transform -translate-x-1/2 bottom-[6%] absolute w-64 text-sm border rounded-lg shadow-sm text-gray-400 bg-gray-800 border-gray-600">
            <div class="p-4">
              <div class="flex items-center justify-between mb-2">
                <%= image_tag 'https://i.imgur.com/vgA2Tut.png', class: 'rounded-full size-12' %>
                <div>
                  <button type="button" class="text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-xs px-3 py-1.5 dark:bg-purple-600 dark:hover:bg-purple-700 focus:outline-none dark:focus:ring-purple-800">Follow</button>
                </div>
              </div>
              <p class="text-base font-semibold leading-none text-gray-900 dark:text-white">
                <a href="#">Thalys Augusto</a>
              </p>
              <p class="mb-3 text-sm font-normal">
                <a href="https://www.linkedin.com/in/nobyte/" class="hover:underline hover:text-cw-purple-500">NoByte-Dev</a>
              </p>
              <p class="mb-4 text-sm">Desenvolvedor Web Full-Stack | Ruby on Rails</p>
              <ul class="flex text-sm">
                <li class="me-2">
                  <p>
                    <span class="font-semibold text-gray-900 dark:text-white">7</span>
                    <span>Followers</span>
                  </p>
                </li>
                <li>
                  <p>
                    <span class="font-semibold text-gray-900 dark:text-white">15</span>
                    <span>Following</span>
                  </p>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </template>
      <div class="flex gap-2">
        <%= locale_set_flag %><a href="https://github.com/NoByte-dev" class="hover:underline hover:text-cw-purple-600" data-action="mouseenter->popover#show mouseleave->popover#hide"><strong>NoByte-Dev</strong></a>
        <p>- Jan/2024</p>
      </div>
    </div>
    <div class="flex gap-1">
      <p>Baseado no curso</p>
      <a href="https://www.udemy.com/user/jackson-pires-de-oliveira-santos-junior/" class="hover:underline hover:text-cw-purple-600" target="_blank">RoR 5.x - <strong>Jackson Pires</strong></a>
    </div>
  </span>
</div>

app/views/layouts/_nav.html.erb
<% language_svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6"> <path fill-rule="evenodd" d="M9 2.25a.75.75 0 0 1 .75.75v1.506a49.384 49.384 0 0 1 5.343.371.75.75 0 1 1-.186 1.489c-.66-.083-1.323-.151-1.99-.206a18.67 18.67 0 0 1-2.97 6.323c.318.384.65.753 1 1.107a.75.75 0 0 1-1.07 1.052A18.902 18.902 0 0 1 9 13.687a18.823 18.823 0 0 1-5.656 4.482.75.75 0 0 1-.688-1.333 17.323 17.323 0 0 0 5.396-4.353A18.72 18.72 0 0 1 5.89 8.598a.75.75 0 0 1 1.388-.568A17.21 17.21 0 0 0 9 11.224a17.168 17.168 0 0 0 2.391-5.165 48.04 48.04 0 0 0-8.298.307.75.75 0 0 1-.186-1.489 49.159 49.159 0 0 1 5.343-.371V3A.75.75 0 0 1 9 2.25ZM15.75 9a.75.75 0 0 1 .68.433l5.25 11.25a.75.75 0 1 1-1.36.634l-1.198-2.567h-6.744l-1.198 2.567a.75.75 0 0 1-1.36-.634l5.25-11.25A.75.75 0 0 1 15.75 9Zm-2.672 8.25h5.344l-2.672-5.726-2.672 5.726Z" clip-rule="evenodd" /></svg>' %>
<div class="bg-cw-purple-900 p-4 flex justify-between items-center relative">
  <div class="flex items-center space-x-4">
    <%= link_to root_path do %>
      <%= image_tag 'logo.png', alt: 'Logo do site', class: 'rounded-full size-16 absolute top-3 left-3 shadow-lg hover:shadow-cw-purple-500/80 hover:brightness-[115%] ease-out duration-500' %>
    <% end %>
  </div>
  <%= render partial: 'shared/breadcrumbs' %>
  <div class="flex items-center space-x-2 text-white font-bold">
    <% if I18n.locale.to_s == 'en-US' %>
    <%= link_to root_path(locale: 'pt-BR'), class: 'hover:text-cw-purple-500 flex gap-1' do %>
      <%= raw language_svg %>
      <%= t('.portuguese') %>
    <% end %>
    <% else %>
      <%= link_to root_path(locale: 'en-US'), class: 'hover:text-cw-purple-500 flex gap-1' do %>
      <%= raw language_svg %>
      <%= t('.english') %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
    <title> <%= breadcrumbs == [] ? 'Crypto Wallet' : breadcrumbs.last.label %></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico', rel: 'app icon', "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

  </head>

  <body class="w-screen h-screen flex flex-col">
    <nav> <%= render partial: 'layouts/nav' %> </nav>
    <%= render partial: 'shared/notifications/success', locals: { message: flash[:notice] } %>
    <%= render partial: 'shared/notifications/errors', locals: { message: flash[:alert] } %>
    <main class="flex-grow overlay-pattern"> <%= yield %> </main>
    <footer> <%= render partial: 'layouts/footer' %> </footer>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= render 'shared/notifications/form_errors', object: @mining_type %>
<%= form_with(model: mining_type) do |form| %>
  <div class="flex justify-center">
    <div class="w-full p-5">
      <div>
        <%= form.label :description, t('.labels.description'), class: 'form-label' %>
        <%= form.text_field :description,  placeholder: 'Nome da moeda', class: 'form-input' %> 
      </div>
      <div>
        <%= form.label :acronym, t('.labels.acronym'), class: 'form-label' %>
        <%= form.text_field :acronym, placeholder: 'Sigla da moeda', class: 'form-input' %>
      </div>
      <div class="flex flex-row items-center justify-between gap-2">
          <%= form.submit t('.submit'), type: :submit, class: "w-1/2 cursor-pointer bg-blue-500 hover:bg-blue-700 text-white py-1 px-4 rounded cursor-pointer" %>
          <%= link_to t('.back'), mining_types_path, type: :button, class: "w-1/2 text-center cursor-pointer bg-blue-500 hover:bg-blue-700 text-white py-1 px-4 rounded cursor-pointer" %>
      </div>
    </div>
  </div>
<% end %>

app/views/mining_types/edit.html.erb
<div class="w-full flex justify-center pt-5">
  <div class="flex flex-col w-[95%] sm:w-[75%] md:w-[50%] lg:w-[40%] xl:w-[25%] p-5 justify-center bg-gray-800 rounded-xl">
    <h1 class="text-white text-2xl pl-5"><%= t('.edit_type') %> #<strong><%= @mining_type.id %></strong></h1>
    <%= render "form", mining_type: @mining_type %>
  </div>
</div>

app/views/mining_types/index.html.erb
<div class="w-full flex justify-center pt-6">
  <div class="w-full sm:w-[75%] md:w-[75%] lg:w-[50%] xl:w-[40%] overflow-x-auto shadow-md rounded-lg">
      <table class="w-full text-sm text-left rtl:text-right text-gray-400">
            <caption class="text-gray-900/80 bg-pattern-tpgraphy bg-current p-5 text-left">
              <div class="flex flex-row justify-between items-center">
                <p class="text-white text-lg font-semibold"><%= t('.mining_types') %></p>
                <%= link_to t('.new_mining_type'), new_mining_type_path, class: "bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded" %>
              </div>
              <p class="mt-1 text-sm font-normal text-gray-400"> <%= t('.types_text') %></p>
            </caption>
          <thead class="text-xs uppercase bg-gray-700 text-gray-400">
              <tr>
                  <th scope="row" class="px-6 py-3">Nome</th>
                  <th scope="row" class="px-6 py-3">Sigla</th>
                  <th scope="row" class="px-2 py-2 text-right" rowspan="2"><%= t('.show_edit') %> </th>
              </tr>
          </thead>
          <tbody>
            <% @mining_types.each do |mining_type| %>
              <tr class="border-b bg-gray-800 border-gray-700 hover:bg-gray-600">
                  <td class="px-6 py-2 font-medium whitespace-nowrap text-white">
                    <%= mining_type.description %>
                  </td>
                  <td class="px-6 py-2">
                    <%= mining_type.acronym %>
                  </td>
                  <td class="px-6 py-2 flex justify-end space-x-2">
                    <%= link_to mining_type do %>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke-width="1.5"
                        stroke="currentColor"
                        class="w-7 h-7 hover:text-cw-purple-500 ease-out duration-500">
                      <path stroke-linecap="round" stroke-linejoin="round" d="m15.75 15.75-2.489-2.489m0 0a3.375 3.375 0 1 0-4.773-4.773 3.375 3.375 0 0 0 4.774 4.774ZM21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                      </svg>
                    <% end %>
                    <%= link_to edit_mining_type_path(mining_type) do %>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke-width="1.5"
                        stroke="currentColor"
                        class="w-7 h-7 hover:text-cw-purple-500 ease-out duration-500">
                      <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
                      </svg>
                    <% end %>
                  </td>
              </tr>
            <% end %>
          </tbody>
      </table>
  </div>
</div>

app/views/mining_types/show.html.erb
<div class="w-full flex justify-center pt-5">
  <div class="flex flex-col p-6 w-[95%] sm:w-[75%] md:w-[50%] lg:w-[40%] xl:w-[25%] justify-center items-center bg-gray-800 rounded-xl">
    <h1 class="text-white text-4xl pl-5"><%= @mining_type.description.titleize %> - <%= @mining_type.acronym %></h1>
    <div class="flex gap-3 items-center w-1/2 pt-4">
      <%= link_to t('.back'), mining_types_path, type: :button, class: "w-full text-center bg-blue-500 hover:bg-blue-700 text-white py-1 px-4 rounded cursor-pointer" %>
      <%= link_to t('.destroy'), mining_type_path, data: {'turbo-method': :delete, 'turbo-confirm': t('alerts.confirmation_msg')}, type: :button, class: "w-full text-center bg-red-500 hover:bg-red-700 text-white py-1 px-4 rounded cursor-pointer" %>
    </div>
  </div>
</div>